### ISSUE TITLE
CORS - configurable Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by artlogic** [Aconex/drakov#101]
Since drakov enforces specified request headers (like Authorization), it would be helpful if either CORS headers could be configured (via a `--header` argument) or auto-configured. Right now I'm manually patching `lib/middleware/response.js` to allow the Authorization header.

I'd be willing to provide a pull request to add in a `--header` argument if it would be accepted.

**Comment by yakovkhalinsky** [comment]
Hey @artlogic was something we had look at putting on our roadmap.

At some point I am thinking I would like to possibly remove or consolidate switches/configuration options that cause header changes in the response for the next minor version update (0.2.0), but for a patch version (0.1.x) I think this would be super useful :+1:

**Comment by artlogic** [comment]
I've submitted a pull request. Let me know if I can do anything else to get this out as a patch to v0.1.

**Comment by artlogic** [comment]
Closed via 7fea735a8ccd88b4ad688c53d2c95cc3762a4fba
