### ISSUE TITLE
Cannot POST issue

### ISSUE THREAD

**Issue by borodaalex** [Aconex/drakov#102]
I have the next api blueprint description that works correctly at app.apiary.io
but fails with drakov saying me:

Cannot POST /login

Tried to call this method via curl like this:
curl -H "Content-Type: application/json" -X POST -d '{"email":"xyz","password":"xyz"}' http://localhost:3000/api/login

or even via postman chrome plugin 
https://drive.google.com/file/d/0ByOLpL4QgNHySDZnaWpkS2IweXM/view?usp=drivesdk

results are the same ((
Cannot POST /login

version of drakov I use is 0.1.16

There are no problem with GET method, only with POST

Below is method description I used:

### Login user into system [POST]

User might be logged into the system using this action. It takes a JSON object containing the next fields:

+ email (string) A user email to be registered in the system.
+ password (string) A user password

This action takes a JSON payload as part of the request as follows:

+ Request (application/json)

            {
                email: "testuser@testuser.com",
                password: "password"
            }

+ Response 201 (application/json)

            {
              "user" : {
                "id" : 32,
                "fullName" : "testuser"
              },             
              "expireAt" : 1447426528063,
              "token" : "token"
            }

**Comment by yakovkhalinsky** [comment]
thank for the report I'll have a look over the next day or so :+1:

**Comment by marcelogo** [comment]
Drakov isn't responding because the Json in the payload is invalid. Both `email` and `password` should be surrounded by double quotes. 

Eg.

```            {
                "email": "testuser@testuser.com",
                "password": "password"
            }```

For your information, this is the parse error from http://jsonlint.com/ : 

```Parse error on line 1:
{    email: "testuser@tes
-----^
Expecting 'STRING', '}'```

There is a grunt plugin that helps to figure out problems like this. As a sugestion:  https://www.npmjs.com/package/grunt-blueprint-validator

**Comment by marcelogo** [comment]
@borodaalex please make that chance and let us know how it goes.

**Comment by borodaalex** [comment]
Hi all, 
I tried both variants: surrounded by double quotes(see my first post  and sample with curl) and without
double quotes(postman plugin)

Results are the same: Cannot POST /login

**Comment by erlanggatjhie** [comment]
Hi Borodaalex!

The reason why we are throwing an error without the double quotes is that we are parsing it to a JSON object which is might be a different approach than what apiary does. 

I do agree that we need to have more logs about it and we are still working on it
