### ISSUE TITLE
Handling multiple actions on a single resource

### ISSUE THREAD

**Issue by borodaalex** [Aconex/drakov#104]
Hi all,

I dont know whether this is issue or it is not supported by drakov right now.

Suppose, we want to describe a variety of error or edge cases a resource might respond with. 
# Message [/messages/{id}]
This resource represents one particular message identified by its *id*.

## Retrieve Message [GET]
+ Response 200 (application/json)

        {"message":"Hello World!"}

+ ﻿Response﻿ 200 (text/plain)

        Hello world!

+ Response 401 (text/plain)

        There is no such a message for you, dear guest.

+ Response 410

        The message you are searching for does not exist anymore.

## Delete Message [DELETE]
+ Response 204

To manage appropriate error responses in apiary you have to use Prefer header.
(see http://support.apiary.io/knowledgebase/articles/117119-handling-multiple-actions-on-a-single-resource  for more details)

And when testing the above case, you should put

Prefer:status=401

And it works as expected.

Does Drakov support multiple responses on a single resource? Cause I tried with prefer header and in case of drakov it ignores this header.
https://drive.google.com/file/d/0ByOLpL4QgNHyS2hLZlRTSW4wRWM/view?usp=drivesdk

Thanks in advance.

**Comment by erlanggatjhie** [comment]
Hi borodaalex!

Yes we currently support multiple responses on a single resource but we have a different approach than apiary. You need to be more explicit in the blueprint file if you want to use the prefer or accept header to response with different scenario. 

For example:

Blueprint file

```
FORMAT: 1A

# Return message

## Things [/messages/{id}]

### Retrieve Message [GET]
First GET example with header 

+ Request

    + Headers

        Prefer: status=200
        

+ Response 200 (application/json)

    + Body

            {"message": "Hello World!"}

+ Request

    + Headers

        Accept: text/plain
        

+ Response 200 (text/plain)

    + Body

            Hello World!

+ Request

    + Headers

        Prefer: status=401

+ Response 401 (text/plain)
        
    + Body

            There is no such a message for you, dear guest.
            
+ Request

    + Headers

        Prefer: status=410

+ Response 410
        
    + Body

            The message you are searching for does not exist anymore.           
            
### Delete Message [DELETE]
      
+ Response 204
```

**Comment by borodaalex** [comment]
erlanggatjhie, thanks for answer!
