### ISSUE TITLE
LINK and UNLINK requests fail

### ISSUE THREAD

**Issue by obihann** [Aconex/drakov#105]
Using the following example:

```md
### Link Network [LINK]

+ Response 200 (application/json)

    + Attributes (User Response)
```

Drakov lists this as a route when it starts however any requests to that route result in an error on the client end stating the socket was reset by a remote peer. Drakov itself doesn't display any output whatsoever.

**Comment by yakovkhalinsky** [comment]
@obihann just following up, we'll have a look at this in the next few days

**Comment by marcelogo** [comment]
@obihann 

We do map LINK and UNLINK methods on Drakov's route handlers.
Unfortunately Drakov does not get called by Express on LINK and UNLINK methods. 

It seems to be an issue with supported methods. This is the module Express uses to list supported methods https://github.com/jshttp/methods/blob/master/index.js

**Comment by yakovkhalinsky** [comment]
Closing as this is a downstream issue in Express.

In future we'll look at implementing either vanila Node.js or another framework that supports more HTTP methods.
