### ISSUE TITLE
Failed to recognize URI variable

### ISSUE THREAD

**Issue by coldmake** [Aconex/drakov#111]
I used the md file below.
When I tried `http://localhost:3000/users`, it gave the json response, but when I tried `http://localhost:3000/users/1`, I got `Cannot GET /users/1`.
It seems that drakov failed to recognize the {id} variable in the URI.

===============================================

FORMAT: 1A

# TEST_API

# Users [/users]

## Obtain User Info [GET /users/{id}]

+ Parameters
    + id (string) ... user id

+ Response 200 (application/json;charset=UTF-8)
    + Body

            {
                "name": "Andy"
            }

**Comment by yakovkhalinsky** [comment]
Apologies @coldmake for the late response, I'll check this out over the next few days :+1:

**Comment by marcelogo** [comment]
@coldmake 

Sorry for the late response.

Drakov expects the attribute in the URL definition. 

Eg
```
#Users [/users/{id}]

## Obtain User info [GET]
```

Could you please give it a go and let us know how it goes.

**Comment by yakovkhalinsky** [comment]
Just pinging @coldmake about this issue.

Will close this in a day or so if no response or we get the all clear.
