### ISSUE TITLE
Load config file automaticilly

### ISSUE THREAD

**Issue by Terenc3** [Aconex/drakov#112]
It would be useful if drakov could automatically load a config file e.g. .drakovrc from the current directory

**Comment by yakovkhalinsky** [comment]
@Terenc3 we have the `--config` options to allow you to specify a configuration file.

E.g. `drakov --config config.js` will look for `config.js` and attempt to load the configuration from there.

I could see that perhaps we could make executing `drakov` on the command line with no arguments look for a `config.js`. Is that what you are suggesting?

**Comment by Terenc3** [comment]
Yes that is what i'm sugessting. To clarify what i mean please refer to JSHint as an example.

> "[..] you can either specify the configuration file manually via the --config flag [or] use a special file .jshintrc [..]" -- http://jshint.com/docs/ (Configuration)

**Comment by yakovkhalinsky** [comment]
Alright sounds like a great idea!

Should be trivial to implement I'll start working on this :+1:

**Comment by yakovkhalinsky** [comment]
Under consideration for 0.2.1

**Comment by yakovkhalinsky** [comment]
@Terenc3 this will be landing in the 0.2.1 release, coming tonight :+1:

**Comment by Terenc3** [comment]
Awesome, thank you :+1:
