### ISSUE TITLE
Invalid JSON schema

### ISSUE THREAD

**Issue by raoulwissink** [Aconex/drakov#113]
After upgrading to `0.20.0` I'm seeing this error:

```
Error: JSON schema is not valid! Invalid type: string (expected object) at path "/properties/type"
    at validateSchema (/drakov/lib/spec-schema.js:14:15)

[...]
```

The error seems to go away if I replace structures like this:

```
# Update [PATCH]
+ Request (application/json)
    + Attributes (object)
        + Include Something
```

With this:

```
# Update [PATCH]
+ Request (application/json)
    + Attributes (Something)
```

Not sure why though... Any ideas?

**Comment by yakovkhalinsky** [comment]
Interesting, I'm admittedly not to familiar with the MSON syntax.

I'll consult some of the other guys who help us maintain Drakov.

**Comment by raoulwissink** [comment]
Thanks! 

Let me know if you need anything (for example some sample code to reproduce the issue).

**Comment by yakovkhalinsky** [comment]
@raoulwissink just following up.

We introduced JSON schema validation on startup of drakov a little while ago, so I can only assume that you might either have an invalid JSON schema or are using an old version of the JSON schema spec.

Drakov uses JSON schema v4.

**Comment by yakovkhalinsky** [comment]
Closing issue.

@raoulwissink let me know if we need to reopen this issue.

**Comment by raoulwissink** [comment]
Well I'm not too familiar with JSON schema, but the code I posted is valid MSON as far as I know. Drakov parses this to JSON schema using Protagonist, so I'll try asking this question over there.

**Comment by yakovkhalinsky** [comment]
The schema validation validates any JSON schema while Drakov starts up.

I'm thinking that maybe I was asking a question along the wrong lines.

Could be that the type declaration is being strict about the Attribute type. It may be requiring the named object type, i.e. `Something`

**Comment by raoulwissink** [comment]
Yeah, unfortunately it's very hard to debug where the generated document fails to validate exactly. For now I've just disabled the schema validator. 

Might it be a good idea to add a `strict` option so this is configurable?
