### ISSUE TITLE
drakov body response, based on Attributes

### ISSUE THREAD

**Issue by PavelPolyakov** [Aconex/drakov#114]
Hi,

In my blueprint api description, I have the next part:
```
+ Response 200 (application/json)
    + Attributes (array[customer])
```

```customer``` is a custom type. When I run ```aglio``` server, I see the next in the generated docs:
![image](https://cloud.githubusercontent.com/assets/839290/12235376/b57acf1a-b873-11e5-926e-042d8504634a.png)

When I run drakov server and do the request, I see the next:
![image](https://cloud.githubusercontent.com/assets/839290/12235386/c2bf9e08-b873-11e5-9fa8-de8397813e04.png)

The content is not autogenerated, based on the type description, as it happens with aglio.
Is that a correct behaviour?

The response is complete, only if I provide the body explicitly:
![image](https://cloud.githubusercontent.com/assets/839290/12235419/eb296248-b873-11e5-8996-feb398f727ea.png)

Could you, please, clarify if it's a correct behaviour?

Regards,

**Comment by PavelPolyakov** [comment]
@yakovkhalinsky , @marcelogo 

Hi guys, could you, please, tell me if it's a correct behaviour?

We are in the middle of the API description and it's quite critical to know if we can use +Attributes (which are more abstract) or we should use +Body if we want to use drakov.

**Comment by yakovkhalinsky** [comment]
@PavelPolyakov drakov currently uses the `Attribute` to just do matching on the request/response pairs.

Drakov doesn't product actual data at this stage. We do have plans to include something like faker.js to do this in the future.

**Comment by yakovkhalinsky** [comment]
Closing issue.

@PavelPolyakov let us know if you still need assistance with this issue :+1:
