### ISSUE TITLE
Not Recognizing Route Overrides

### ISSUE THREAD

**Issue by adamgoose** [Aconex/drakov#115]
My truncated api markdown file can be viewed here: http://d.enge.me/13wdO+

Notice how the `##` header defines the route as `/`, but the 2nd `###` header overrides that route to `/routes`. This works in Apiary, however Drakov isn't recognizing it properly. When starting Drakov, I get the following (truncated) console output:

```
$ sudo drakov -f ./futr.md -p 999 --discover --disableCORS
   DRAKOV STARTED
[LOG] Setup Route: GET / Get API Details
[LOG] Setup Route: GET / Get API Routes
   Drakov 0.2.0      Listening on port 999
```

When making a `GET /routes` request, Drakov returns a 404.

**Comment by yakovkhalinsky** [comment]
@adamgoose would you be able to post a sanitized version of the blueprint file or email me directly `yakov at therocketsurgeon.com` and I'll try it out.

**Comment by adamgoose** [comment]
@yakovkhalinsky You can click the link in my comment above, and it'll spit out the first chunk of my file. It's only truncated, not manipulated in any other way.

**Comment by yakovkhalinsky** [comment]
@adamgoose I've got the file and can reproduce the problem.

Will post again once I know more :+1:

**Comment by yakovkhalinsky** [comment]
@adamgoose check this public GIST https://gist.github.com/yakovkhalinsky/1378abe4f8e05dbdfb37/revisions

Subtle difference is that the `##` specifies the endpoint, and then the `###` specifies the method.

Let me know if you are still having trouble after you make this change :+1:

**Comment by yakovkhalinsky** [comment]
Closing as a lapsed question.

@adamgoose let me know if you still need help with this issue :+1:
