### ISSUE TITLE
drakov - how to include files recursive

### ISSUE THREAD

**Issue by PavelPolyakov** [Aconex/drakov#116]
Hi,

I have the next files structure:
![image](https://cloud.githubusercontent.com/assets/839290/12299147/b2d3bca6-ba15-11e5-8fe6-35054281c051.png)

customers/index.apib is included inside the ```index.apib``` file.
![image](https://cloud.githubusercontent.com/assets/839290/12299175/d5675336-ba15-11e5-96dd-2997d54e4129.png)

I assume this is not a part of the standard, however, aglio uses it.

I try to run ```drakov``` like this:
```
drakov -f *.apib
```

However, it doesn't see the content from the customers/index.apib file.

How can I run drakov in the way that directories are parsed recursively?

Regards,

**Comment by PavelPolyakov** [comment]
I found that in aglio you can do the next:
```
aglio -i input.apib --compile -o full.apib
```

to have your project to be compiled to one file

**Comment by yakovkhalinsky** [comment]
Hi @PavelPolyakov the `-f` switch supports passing glob expressions so something like `"dir/**/*.apid"` should pickup files in all those directories.
