### ISSUE TITLE
segmentation fault  drakov - how to debug?

### ISSUE THREAD

**Issue by PavelPolyakov** [Aconex/drakov#117]
Hi,

I have a long blueprint which is parsed by https://apiary.io/ and fails with drakov.

Basically, I have a long ```# Data Structures``` section, and after the line N, any new data structure which I add results to the segmentation fault.

![image](https://cloud.githubusercontent.com/assets/839290/12303036/9a794b86-ba28-11e5-9ae8-e3d6b6994f4a.png)

How can I try to debug that?

Regards,

**Comment by yakovkhalinsky** [comment]
@PavelPolyakov how many lines do you have in your file? I could try to replicate this by creating a file with the same sized file

**Comment by PavelPolyakov** [comment]
I have 316 lines in my file.

I have cut it down especially to test why it fails, so 300 lines are data-structures and only 10+ lines are REST specifications.

**Comment by yakovkhalinsky** [comment]
Hmmm that's interesting.

I think we could try streaming in the file, at the moment we load it, but even that many lines shouldn't be too much.

I'll have to try a few things out and see what we can find :+1:

**Comment by yakovkhalinsky** [comment]
@PavelPolyakov having a look at this today, can you tell me your OS and Node.js version?

**Comment by PavelPolyakov** [comment]
macos, node 4.2

**Comment by yakovkhalinsky** [comment]
@PavelPolyakov I've tried with a blueprint file that has a lot of lines and I don't get a segfault.

Is it possible for you to email me the file at `yakov at therocketsurgeon dot com` and I will test it.

It did once get a segfault when I switched node.js version, but I don't believe this is the cause.

We do synchronously read in the whole file, which isn't optimal, this may be the cause, so I am guessing file size is a part of the issue.

**Comment by PavelPolyakov** [comment]
@yakovkhalinsky 

Hi, interesting, that on my home macbook pro, where I have just tested, it has not crashed.
But it fails in my mac mini.

Later I will try to compare nodejs version or anything else, but for now I think they are alike.

Thanks

**Comment by yakovkhalinsky** [comment]
@PavelPolyakov I'll leave this open for another day or so and then close as we've been unable to reproduce this issue.
