### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by skawaguchi** [Aconex/drakov#15]
I think it's fairly important to be able to support CORS. It should probably be configurable as well. I don't mind making a pull request unless this is already in the works.

**Comment by yakovkhalinsky** [comment]
Definitely agree with this. We originally built this tool for our own particular use case, but since we've open source it, I'd love to see this become useful for all API blueprint implementations.

We'll review your #17 pull request and get it in as soon as we can. :+1:

**Comment by skawaguchi** [comment]
Cool. One other item to consider is optional SSL support as well.

**Comment by yakovkhalinsky** [comment]
Yep excellent suggestion. I'll an issue for that one :+1:

**Comment by yakovkhalinsky** [comment]
PR #17 has been merged
