### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by viktomas** [Aconex/drakov#150]
This is a feature request.

Drakov IMHO needs an opposite of `--stealthmode`. When using drakov, following scenario occur very often:

Drakov is not matching any of the loaded specifications and there is no way to figure out what exact request drakov receives.

I always have to change the drakov source code by adding a custom middleware at this line https://github.com/Aconex/drakov/blob/master/lib/drakov.js#L23 and logging `request.body` and `request.headers`.

It would be great to implement flag

`--debug`

that would log exact request coming in in the same way as it uses it for matching against API specification. That would save a lot of time and effort when debugging.

I'm happy to implement the feature as long as it is considered beneficial by other people.

**Comment by yakovkhalinsky** [comment]
Closing, please refer to #154 for more info
