### ISSUE TITLE
URI conflict

### ISSUE THREAD

**Issue by zqhong** [Aconex/drakov#175]
I have project foo and project bar, they both have api `GET /search`. For this case, `drakov` will conflict as repeat URI.

So how to add prefix for URI. Such as, for project foo, the API is `GET /foo/search`. And for project bar, the API is `GET /bar/search`.

Or using the host for differentiate project foo and project bar. Like this, `GET http://mock.foo.com/search` will match project foo API. And `GET http://mock.bar.com/search` will match project bar.

Now, I used a dirty way. Before running `drakov`, copy document to the temp folder. Then, using `sed` command for replace resource API.

**Comment by aj-jaswanth** [comment]
Why don't you want to set `foo` as the context path for that service?

**Comment by zqhong** [comment]
Sorry, I forgot why I want to do this.
