### ISSUE TITLE
 Could not load the Visual C++ component "VCBuild.exe". To fix this

### ISSUE THREAD

**Issue by mossila** [Aconex/drakov#176]
After I npm install this package and I found this. 
```
Could not load the Visual C++ component "VCBuild.exe". To fix this
1) install the .NET Framework 2.0 SDK, 
2) install Microsoft Visual Studio 2005 or 
3) add the location of the component to the system path if it is installed elsewhere.
```

My system is Windows 10 with visual studio 2017 installed 

npm version = 5.4.2
node version = 6.11.2

**Comment by Dashue** [comment]
Run using powershell as admin
```npm install --global --production windows-build-tools```

This will take a couple of minutes

**Comment by aj-jaswanth** [comment]
@mossila Has your issue been fixed?
