### ISSUE TITLE
Missing URI parameters on mock advanced API Blueprint resources

### ISSUE THREAD

**Issue by kamihouse** [Aconex/drakov#178]
Hi guys.
I'm having some troubles while trying to mock some resources using the Blueprint API.

This resource is defined by a resource name (identifier) followed by an HTTP request method and an URI template enclosed in square brackets []:

`# <identifier> [<HTTP request method> <URI template>]`
Source: https://apiblueprint.org/documentation/specification.html#def-resource-section

For example:

``` markdown
## Group Veículos
Descrição dos recursos de veículos.


### Avisos [/veiculos/{id}/avisos]

+ Parameters
    + id: `wqv57dm` (required, string) - ID do veículo.

#### Lista os avisos [GET]
Esse endpoint projeta uma lista de avisos especificado pelo veículo.

+ Response 200 (application/json; charset=utf-8)
    + Attributes
        + data (array[dsAvisoVeiculoResponse], fixed-type)

### Deleta um aviso [DELETE /veiculos/{id}/avisos/{id_aviso}]
Esse endpoint deleta um aviso especificado.

+ Parameters
    + id: `wqv57dm` (required, string) - ID do veículo.
    + id_aviso: `wqv57dm` (required, string) - ID do aviso.

+ Response 204
```

**This generates the doc:**
![recursos](https://user-images.githubusercontent.com/892340/36322129-60490f1c-1333-11e8-87c5-e0671d1f3bb8.png)

**However, drakov generates the following endpoints:**
![drakov](https://user-images.githubusercontent.com/892340/36322232-b60e2eb4-1333-11e8-91d8-5dad4df8d165.png)
Path variables are not being interpreted.

Now I'm having some troubles to mock the features and I do not know if it's a drakov or Blueprint API problem. Thanks.

**Comment by LKDevelopment** [comment]
Did you find any solution for this? I have the same problem as you.

**Comment by LKDevelopment** [comment]
@kamihouse 

I fixed it currently hardcoded:
For my use case this now work. I'll try to find a more generic solution.
https://github.com/LKDevelopment/drakov/commit/a3e359071fd89b35551cd9ab6d06d2c7fa335df2

**Comment by kamihouse** [comment]
Hi @LKDevelopment, In my case I stopped using action along with resources.
But I really enjoyed your proposed solution at https://github.com/LKDevelopment/drakov/commit/a3e359071fd89b35551cd9ab6d06d2c7fa335df2 \o/

For example:  
`### Deleta um aviso [DELETE /veiculos/{id}/avisos/{id_aviso}]`

I solved by separating the feature from the action:

`### Aviso [/veiculos/{id}/avisos/{id_aviso}]`
...

`#### Deleta um aviso [DELETE]`
...

**Comment by LKDevelopment** [comment]
i ve found out that there is already a better generic pr here in the repo :) #169	I've use now this code and it works perfectly!
