### ISSUE TITLE
Add "Access-Control-Allow-Methods" for available methods

### ISSUE THREAD

**Issue by TUNER88** [Aconex/drakov#26]
I try to `DELETE` angular resource, and get following error in Chrome Console.

```
XMLHttpRequest cannot load http://localhost:8080/concepts/12. Method DELETE is not allowed by Access-Control-Allow-Methods.
```

If i add Allow-Methodes header in `request.js` everything works fine.

```js
exports.headers = function(req, res, next) {
    res.set('X-Powered-By', 'Drakov API Server');
    res.set('Access-Control-Allow-Methods','DELETE'); // fix Allow-Methods error
    next();
};
```

It would be nice, if you can dynamically add Header for all available methods

![screen shot 2015-02-11 at 15 00 36](https://cloud.githubusercontent.com/assets/1565397/6148193/a341a4b6-b1ff-11e4-9b87-c4a9da3a6165.png)

**Comment by yakovkhalinsky** [comment]
definitely a quick win, will get that in for the next milestone release :+1:

**Comment by yakovkhalinsky** [comment]
Have added this into #29 

Just waiting for the build to go green, then I will merge it into master.

You can expect this to be available via npm on Saturday :+1:

**Comment by TUNER88** [comment]
Awesome support, thx!!!
