### ISSUE TITLE
Add watch flag to reload API

### ISSUE THREAD

**Issue by ghost** [Aconex/drakov#40]
It would be nice to have drakov reload if any of the glob pattern matches change.

**Comment by yakovkhalinsky** [comment]
Investigating different approaches, will try and get this into the next milestone :+1:

**Comment by yakovkhalinsky** [comment]
Just an update on this issue, we have some code in the works, but need more time to setup a nicer way of testing child processes, so hopefully this is something we can bring in, in the near future :+1:

**Comment by hendrikmaus** [comment]
+1

**Comment by yakovkhalinsky** [comment]
Thanks for the feedback guys, we are definitely looking at getting this feature into drakov in the short term.

**Comment by shavo007** [comment]
+1 on this.

I have a watch in grunt and stop/start the server but doesnt seem to reload.

```
   watch: {
      drakov: {
        files: ['doc/track-api.md'],
        tasks: ['mock-api'],
        options: {
          livereload: '<%= connect.options.livereload %>'
        }
      }
```

Grunt task

```
  grunt.registerTask('mock-api', 'Start drakov server', function() {
    var done = this.async();

    drakov.stop(function(){
      console.log('-- STOPPED --');
    });

    var drakovOptions = {
      sourceFiles: './doc/*.md',
      serverPort: 3000,
      autoOptions: true,
      delay: 1000,
      disableCORS: true
    };

    drakov.run(drakovOptions, function(err){
      console.log('-- STARTED --');
      if (err) {
        throw err;
      }
    });
    done();
  });
```

I see in the console 

>> File "doc\track-api.md" changed.
Running "mock-api" task
-- STOPPED --
   DRAKOV STARTED   

Done, without errors.

But it doesnt seem to reload!!! ;-)

**Comment by shavo007** [comment]
Any update on this guys?

**Comment by yakovkhalinsky** [comment]
hey @shavo007 we have some code to do this, but were unable to reliably test it.

I'll have a look at this again and look at introducing this.

**Comment by shavo007** [comment]
No probs. Thanks for the reply.
