### ISSUE TITLE
Automatically respond to OPTIONS requests

### ISSUE THREAD

**Issue by dialelo** [Aconex/drakov#43]
Wouldn't it make sense to automatically respond to `OPTIONS` requests? Drakov knows about the HTTP methods that a certain URL can respond to so it can provide `Allow` and `Access-Control-Allow-Methods` headers in the response.

If this is possible/desirable I'd be happy to work on a patch for implementing it.

**Comment by yakovkhalinsky** [comment]
Hi @dialelo Drakov has the `method` argument, which adds the  `Access-Control-Allow-Methods`, I'm not sure if there is a specific use case where would need to automagically respond the the `OPTIONS` header.

We prefer that Drakov respects the blueprint files themselves.

Let me know your thoughts.

**Comment by dialelo** [comment]
> We prefer that Drakov respects the blueprint files themselves.

Makes sense, although documenting `OPTIONS` requests for every URL in the API can get a bit tedious. Since you have access to the metadata required for `Access-Control-Allow-Methods` and `Access-Control-Allow-Headers` i thought it'd be cool to automatically respond to `OPTIONS` requests.

**Comment by matthewwithanm** [comment]
@yakovkhalinsky The specific use case is [preflighted requests][1]. Normally this isn't something you'd want to have to specify for every resource; it's more of a global API setting (usually accomplished with middleware) with other CORS handling.

[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

**Comment by dialelo** [comment]
Exactly.

**Comment by yakovkhalinsky** [comment]
Mmm reading that info on the preflighted requests, it makes sense.

We'll have a look at this and look at incorporate something in a release for next week :+1:

**Comment by dialelo** [comment]
Great news, glad to read that.

**Comment by matthewwithanm** [comment]
Awesome, thanks!

**Comment by MichielDeMey** [comment]
:+1: I was also looking for this feature.

**Comment by mistm** [comment]
I submitted pull request for this here: https://github.com/Aconex/drakov/pull/59

**Comment by yakovkhalinsky** [comment]
Dealt with in PR #59

**Comment by dialelo** [comment]
Great, thanks for your time!

**Comment by yakovkhalinsky** [comment]
A bit thank you to @MartinNuc for his PR to add this feature :+1:
