### ISSUE TITLE
Dredd fails because of setting encoding

### ISSUE THREAD

**Issue by gillesdemey** [Aconex/drakov#44]
Currently, when running Dredd on a Drakov instance it reports that the `Content-Type` header is incorrect. 

This is because Express adds `; charset=utf-8` to the `Content-Type` header when setting the encoding on the request object (https://github.com/Aconex/drakov/blob/master/lib/middleware/request.js#L6).

Any particular reason why we're explicitly setting the encoding and not honoring the blueprint? 

```json 
request:
body:

headers:
    User-Agent: Dredd/0.4.7 (Darwin 14.3.0; x64)

uri: /notes
method: GET


expected:
headers:
    Content-Type: application/json

body:
[
  {
    "id": 1,
    "title": "Jogging in park"
  },
  {
    "id": 2,
    "title": "Pick-up posters from post-office"
  }
]
statusCode: 200


actual:
statusCode: 200
headers:
    x-powered-by: Drakov API Server
    access-control-allow-origin: *
    content-type: application/json; charset=utf-8
    content-length: 104
    etag: W/"68-91519068"
    date: Sat, 14 Mar 2015 22:59:49 GMT
    connection: keep-alive

body:
[{
  "id": 1, "title": "Jogging in park"
}, {
  "id": 2, "title": "Pick-up posters from post-office"
}]
```

Updating the blueprint to reflect the charset works fine, but it feels like we should support more than just utf-8 encoded payloads.

**Comment by yakovkhalinsky** [comment]
Good question @gillesdemey there's requirement to set the charset in the response.

Just curious, may I ask why you are running Dredd against Drakov?

**Comment by yakovkhalinsky** [comment]
I think if there is no good reason for us to set the character encoding we can take that line out :+1:

**Comment by gillesdemey** [comment]
No particular reason, I just wanted to give Dredd a try and I didn't want to create an express application — so Drakov seemed like the perfect solution :)

**Comment by marcelogo** [comment]
@gillesdemey We have removed the encoding from the request. Turns out, however, that Express implicitly adds a the default character encoding on all responses if it is not specified.

Perhaps this is something which Dredd should not enforce on this particular header.

We are going to do a spike in here but we are not sure if it is something Drakov could address.

**Comment by marcelogo** [comment]
@gillesdemey

We figured out that Express explicitly sets the charset to `utf-8`. https://github.com/strongloop/express/blob/master/lib/response.js#L148

Even when the response body is an object. It converts it to string and call send again.
https://github.com/strongloop/express/blob/master/lib/response.js#L233

As we understand that Drakov must strictly follow what is defined in the blueprint file, we decided to handle it and we have pushed a fix to this scenario. https://github.com/Aconex/drakov/commit/9a49bc85e6fd7ea4040514805d7bfd90cea6e03e

It should address your situation with Dredd. 

Let us know how it goes.

**Comment by gillesdemey** [comment]
I'll check it out again tonight and I'll let you know.

I didn't know that Express actually looked at the response body type, interesting :)

Thanks for all the effort you've put into this, even though I understand that the use-case is pretty weird.

**Comment by gillesdemey** [comment]
The fix is working, no more fails! :+1:
