### ISSUE TITLE
Required params and GET methods

### ISSUE THREAD

**Issue by charly-palencia** [Aconex/drakov#53]
### Example
If i create something like this:

```markdown
.
.
.
## Car [/api/car/{id}{?color}] 
+ Parameters 
  + id: `12` (string,required) 
  + color: `red` (string,required) 
.
.
.
.
```

#### Expected behaviour 
**When** i send a request like ```get /api/var/12```
**Then** i should receive some error about validate parameters 

#### Problem
If i send the request above i'm receiving a valid request(200 status response). is that ok? (i'm new with drakov. so, i want to be sure that i'm not doing anything wrong (probably i did )

thanks for you help

**Comment by yakovkhalinsky** [comment]
Hi @charly-palencia the way it works is drakov matches from specific to less specific.

That way you can have request/response pairs for different combinations of query parameters.

In you case it means that a GET with no query parameters will still match.

Hope that makes sense :8ball:

**Comment by charly-palencia** [comment]
yeah! that's what i need!  thank you so much @yakovkhalinsky !
