### ISSUE TITLE
Add a flag to specify binding address

### ISSUE THREAD

**Issue by jaysonsantos** [Aconex/drakov#54]
Somewhere between version 0.1.3 and 0.1.5 drakov stopped listening on 0.0.0.0, which is useful in docker for example, if the default behaviour now is 127.0.0.1 it think that is good to have a flag to specify the listening address as it is impossible to run drakov on docker now.

**Comment by yakovkhalinsky** [comment]
Hi @jaysonsantos right you are.

I will look at this now, patch and publish ASAP to npm to address this.

On a side note, I'd be interested to hear about your usage of drakov via docker.

**Comment by yakovkhalinsky** [comment]
PR #55 should address this.

Will do a little bit of testing and then send this up to NPM :+1: 

Sorry for the breakage.

**Comment by yakovkhalinsky** [comment]
OK I have tested the code with the PR and done some housekeeping.

Will be releasing 0.1.6 which will include a fix for using drakov on a public IP interface :+1:

**Comment by jaysonsantos** [comment]
Hi @yakovkhalinsky thank you :)
About the docker part, we are using it there because we run a container with drakov and aglio so mobile/frontend developers don't have to install the whole stack in their machines.
