### ISSUE TITLE
Wrong query string handling

### ISSUE THREAD

**Issue by Art4** [Aconex/drakov#58]
Drakov seems to still have problems with query string parameters. As you can see [in this build](https://travis-ci.org/Art4/youthweb-api/jobs/64205762) Drakov should register these 3 Urls from the Blueprint API file.

```
GET /index.php?action=stats&cat=account # Retrieve the account stats
GET /index.php?action=stats&cat=forum # Retrieve the forum stats
GET /index.php?action=stats&cat=groups # Retrieve the groups stats
```

The first request runs well, but at the second and third request Drakov returns the wrong responses.

**1st request**: All right
```
[LOG] GET /index.php?action=stats&cat=account
[DRAKOV] GET /index.php?action=stats&cat=account Retrieve the account stats
```

**2nd and 3rd request**: Returns the first response?

```
[LOG] GET /index.php?action=stats&cat=forum
[DRAKOV] GET /index.php?action=stats&cat=account Retrieve the account stats
```
```
[LOG] GET /index.php?action=stats&cat=groups
[DRAKOV] GET /index.php?action=stats&cat=account Retrieve the account stats
```

Is this a bug or am I doing something wrong? Oh, and please don't judge me for these crappy urls. :pensive: They came from a legacy project and will hopefully change in near future.

**Comment by yakovkhalinsky** [comment]
hi @Art4 drakov doesn't really understand query parameter values yet, although it is on our roadmap.

Unfortunately it is only matching the keys in your query string.

**Comment by yakovkhalinsky** [comment]
Am closing this as this is expected behaviour.

@Art4 let me know if you have any other questions about this issue :+1:

**Comment by Art4** [comment]
Why it is necessary for drakov to understand the query parameters? I thought the url and the response could be stored in an arraylike way.

Url_with_querystring => API blueprint response

**Comment by yakovkhalinsky** [comment]
have a look at our Blueprint API file that we use to test the functionality:
https://github.com/Aconex/drakov/blob/master/test/example/md/query-parameters.md

Drakov only sees `?action&cat`
