### ISSUE TITLE
Middleware not exposed?

### ISSUE THREAD

**Issue by matthewwithanm** [Aconex/drakov#62]
[index.js][1] exports the middleware, but [package.json][2] doesn't use that for its [`main` field][3]. Also, the express middleware example has you using the drakov module itself, though that doesn't have an `init` method.

[1]: https://github.com/Aconex/drakov/blob/c23a70d9e3e0d7a249071be8479158cc54af1f37/index.js
[2]: https://github.com/Aconex/drakov/blob/c23a70d9e3e0d7a249071be8479158cc54af1f37/package.json
[3]: https://github.com/Aconex/drakov/blob/c23a70d9e3e0d7a249071be8479158cc54af1f37/package.json#L5

**Comment by yakovkhalinsky** [comment]
@matthewwithanm that example may be out of date.

I'll try and make some time to address this :+1:

**Comment by yakovkhalinsky** [comment]
@matthewwithanm looked at this and you are 100% correct, package.json needs to be updated :+1: 

I'll put this change into the 0.1.8 release coming up tomorrow :dancers:

**Comment by matthewwithanm** [comment]
Cool, thanks!

**Comment by yakovkhalinsky** [comment]
Fixed in commit https://github.com/Aconex/drakov/commit/e3b00ef803de0f0681a08a0f1c7864666082da68

Will be included in version 0.1.8
