### ISSUE TITLE
Find a better way to get feedback and ideas from the community

### ISSUE THREAD

**Issue by yakovkhalinsky** [Aconex/drakov#63]
I feel like we still have a lot we can do, but I'm not sure just posting issues is good enough.

Would love to hear from people either using or wanting to use Drakov about possible way to communicate with a community of users and potential users.

**Comment by Art4** [comment]
* IRC
* Mailinglist

**Comment by yakovkhalinsky** [comment]
IRC might be good.

In regards to a mailing list, maybe a discussion app that does a daily/weekly digest via email (e.g. Google Group)?

Good stuff, keep it coming :+1:

**Comment by yakovkhalinsky** [comment]
Have setup a google group, we'll see how it goes
https://groups.google.com/forum/?hl=en#!forum/drakov-api-server
