### ISSUE TITLE
I am new to mock server setup. Cannot get Drakov to work...

### ISSUE THREAD

**Issue by amanjyo** [Aconex/drakov#64]
My .md file is very basic.
---------------------------------------------------------------------------------------
```
FORMAT: 1A

# Fleetfoot API
This is the API Blueprint file for fleet foot API services.

# Group Login

## Login page [/]

### Get Login page [GET]

+ Response 200
```

I see Cannot GET /  when I try... .What could be the problem? I am starting from command line. The output in the window is

   DRAKOV STARTED   
[LOG] Setup Route: GET / Get Login page
   Drakov 0.1.7      Listening on port 3000
[LOG] GET /

**Comment by yakovkhalinsky** [comment]
hi @amanjyo thanks for your question, I'll check it out and get back to you soon :+1:

**Comment by yakovkhalinsky** [comment]
@amanjyo could you please copy/paste the startup command you are using into a comment here?

**Comment by yakovkhalinsky** [comment]
@amanjyo I found that Drakov responded ok, just the browser didn't know how to handle the content of the response.

You should try and always have a content type in your response like so:

`+ Response 200 (application/json;charset=UTF-8)`

**Comment by amanjyo** [comment]
Thank you for the response.   I added the content type still I got the "404 Not Found"  response from server.  I have other .md files which return json structures etc, they all have the content types defined. Those also did not work for me.  The one I posted here was the simplest I was trying.  The command I am starting drakov with is

~/node_modules/drakov/drakov -f   login.md

**Comment by yakovkhalinsky** [comment]
@amanjyo what operating system and node.js version are you using?

Could you also email me yakov at therocketsurgeon.com with the file you are trying to use and I'll try it with the same node.js version.

**Comment by amanjyo** [comment]
I sent the mail.

**Comment by yakovkhalinsky** [comment]
Just resurfacing this issue, as the user is still unable to get a working setup
