### ISSUE TITLE
cannot run drakov 

### ISSUE THREAD

**Issue by shavo007** [Aconex/drakov#65]
Hi,

I am really struggling to get this to work!

I resolved all the issues I had trying to install this module on Windows 8.1. 

Then I tried to run the module with an blueprint file I used from this project.

Cmd is:
```
drakov -f "./simple-api.md"
```

I was expecting to access it at localhost:3000/api/things
I get this error now:

```
{ code: 2,
  message: 'the use of carriage return(s) \'\\r\' in source data isn\'t currently supported, please contact makers',
  location: [ { index: 10, length: 1 } ] }
```

i assume this is issues with line endings? 
Is it possible to run this at all in windows!!?

node version is 0.12.5
npm is 2.11.2

Any help is appreciated as Im banging my head here... ;-)

Thanks,
Shane.

**Comment by shavo007** [comment]
I resolved it!!

In my git config I had core.autocrlf set to true. 
Once I changed this to input, it worked!!!!

**Comment by yakovkhalinsky** [comment]
ah nice one @shavo007 :+1: good that you posted an issue, hopefully other Windows users may be able to find this

**Comment by shavo007** [comment]
This was a nightmare to get working on windows!!! ;-)

**Comment by shavo007** [comment]
@yakovkhalinsky  Is it easy to return different responses based on the uri parameter? 
I dont want the consumer of this to have to pass in a request header.  (Prefer:status=XXX)

Cheers,
Shane.

**Comment by yakovkhalinsky** [comment]
hi @shavo007 in regards to your parameter question, drakov doesn't understand parameter values, just the key, although this is on our roadmap.
