### ISSUE TITLE
Grunt task for starting drakov

### ISSUE THREAD

**Issue by shavo007** [Aconex/drakov#66]
Hi,

I have registered a basic task for starting drakov. I include this task when I call grunt serve.

Does the below config look ok to you?

```javascript


  grunt.registerTask('mock-api', 'Start drakov server', function() {
    var drakovOptions = {
      sourceFiles: './test/example/**/*.md',
      serverPort: 3000
    };

    drakov.run(drakovOptions, function(err){
      if (err) {
        throw err;
        console.log('-- STARTED --');
      }
    });
  });

  grunt.registerTask('serve', 'Compile then start a connect web server', function (target) {


    if (target === 'dist') {
      return grunt.task.run(['build', 'connect:dist:keepalive']);
    }

    grunt.task.run([
      'mock-api',
      'clean:server',
      'wiredep',
      'concurrent:server',
      'autoprefixer:server',
      'connect:livereload',
      'watch'
    ]);
  });

```

**Comment by shavo007** [comment]
I cant add a label; but this is a question!! ;-)

**Comment by yakovkhalinsky** [comment]
The trick with using these kinds of grunt tasks is to make the work in async.

At the top of the function you need:
`var done = this.async();`

And then call done when the async task is finished:
`done()`;

Have a look at http://gruntjs.com/creating-tasks for a reference.

**Comment by yakovkhalinsky** [comment]
I'm not entirely sure how grunt will react with having a drakov server in a watch.

You may need to use a grunt plugin that runs things in child processes.

Let me know how you go.

We've made a grunt plugin to run protractor tests with drakov, you can use that as a reference as well:
https://github.com/Aconex/grunt-blueprint-test-runner/blob/master/tasks/blueprint_test_runner.js

**Comment by shavo007** [comment]
Cheers for the reply mate. I made the task async. 

```javascript

grunt.registerTask('mock-api', 'Start drakov server', function() {
    var done = this.async();

    var drakovOptions = {
      sourceFiles: './doc/*.md',
      serverPort: 3000
    };

    drakov.run(drakovOptions, function(err){
      console.log('-- STARTED --');
      if (err) {
        throw err;
      }
    });
    done();
  });


```
