### ISSUE TITLE
respect directory structure

### ISSUE THREAD

**Issue by kosmotaur** [Aconex/drakov#68]
Hi there!

It's noths.com here. 
Our APIs need versioning, so the URLs will be prepended by the likes of "v1", "v2". The mock APIs will be exposed under all supported versions. We don't want to have a flat file structure with the same resource in multiple versions, like:

```
.
|____address-v1.md
|____address-v2.md
|____address-v3.md
|____checkout-v1.md
|____checkout-v2.md
|____checkout-v3.md
```
as this would get out of hand with hundreds of files pretty quickly. Also, multiple services we're running could have a resource with the exact same name, like `/address`, so managing the names would become even more tricky.

We would like to organise them to indicate service/version/resource, like this:
```
.
|____checkout
| |____v1
| | |____address.md
| | |____checkout.md
| |____v2
| | |____address.md
| | |____checkout.md
| |____v3
| | |____address.md
| | |____checkout.md
|____suppliers
| |____v1
| | |____address.md
| |____v2
| | |____address.md
| |____v3
| | |____address.md
```

We would like to add an option called eg. `prepend-paths`, so that the file system path gets prepended to the actual endpoints' URLs, so we'd get something like these given the directory structure just above:

```
GET /checkout/v1/address
GET /checkout/v1/checkout
GET /checkout/v2/address
GET /checkout/v2/checkout
GET /checkout/v3/address
GET /checkout/v3/checkout
```
and
```
GET /suppliers/v1/address
GET /suppliers/v2/address
GET /suppliers/v3/address
```

We're happy to do all the coding, just let us know if you'd welcome such an option.

Kind regards,
@SiCurious and @kosmotaur

**Comment by yakovkhalinsky** [comment]
Hey @kosmotaur that actually sounds like a useful feature :+1: 

How about including it as an extra option/argument, in addition to the `-f` option.

**Comment by yakovkhalinsky** [comment]
Just been discussing this and we are thinking carefully about how this effects our policy of `respect the spec files`.

I'm starting to think this would bring some confusing behaviour to Dravko and would endanger the simplicity of just obeying what is in the specs.

There is currently nothing stopping you from breaking up your spec files into separate directories as the `--file` or `-f` argument takes a glob expression that can load files nested inside a directory/folder structure.

ping @SiCurious

**Comment by SiCurious** [comment]
The key reason we cannot use the `-f` option is that we are not running the Drakov server locally, it is hosted on a company-wide accessible server.
We have a CI pipeline around the blueprints themselves, so that whenever we agree on a change to the APIs, they get deployed automatically. All of them are accessible to the whole company. We cannot at a given point in time just use a glob to now run `v1` or anything along these lines. We need all blueprints accessible at all times, so that different clients can be developed and automatically tested against them.
As to the "respect the spec files" policy, that's why this would be an option, so by default you keep your policy, but also allow for flexibility in a larger, industry scale use case.

@SiCurious and @kosmotaur

**Comment by yakovkhalinsky** [comment]
Are the actual endpoints the same in each version?

Would it possible to run multiple servers?

**Comment by kosmotaur** [comment]
We could work on a `drakov-cluster` module, which could spin up multiple instances of Drakov, do the pre-routing and proxy the requests into the respective instance. 
Quite a bit of overhead though, so we'll need to consider this vs. forking Drakov if it's a no-go for you.

**Comment by yakovkhalinsky** [comment]
The `drakov-cluster` idea is intriguing.

A recent PR that I did added support for using a config file, this will make it easier to load multiple configurations if needed.

This idea appeals to me as it would allow us to keep the basic functionality of `drakov` the same.

If that is the solution to you guys, I'm happy to work on that for the next release.

**Comment by yakovkhalinsky** [comment]
@SiCurious @kosmotaur see #72 

I'm happy to discuss this in more detail in the new issue that I have created.
