### ISSUE TITLE
Parametric headers or looser value matching.

### ISSUE THREAD

**Issue by xiphiaz** [Aconex/drakov#75]
Is it possible to have the same loose matching on route segments with parameters for matching against headers?

I have a use case where one of the required request headers is an `Authorization: Bearer <token>` header, but the`<token>` can change for many different reasons.

Is it possible to loose matching on the headers?

**Comment by yakovkhalinsky** [comment]
Thanks for the question @xiphiaz we'll discuss this over the next week and we'll have a look at how easy it will be to implement, and respond in this issue as to our thoughts :+1:

**Comment by marcelogo** [comment]
@xiphiaz 

I wonder if you are also using your contract files for documentation purposes.

If you are only describing scenarios you could double that example and make another one without `Authorization` header. 

Eg

```FORMAT: 1A

# Link and Unlink

## A rest resource [/api/resource]

### Link it [GET]

+ Request
    
    + Headers
    
            Authorization: something

+ Response 204 

+ Request

+ Response 201 
```

In this case when Drakov cannot match the Authorization header it will fallback to the second example.

Would that anyhow help you?

We are closing this issue. 

Please let us know if you need help.

**Comment by xiphiaz** [comment]
@marcelogo The scenario is the use of drakov to mock an api that requires authorization. Without this feature it means I would have to set the authorization header to a fixed value defined in the contract file. It's not really a big problem, it just makes for an extra step the use drakov as a mock
