### ISSUE TITLE
POST request attempts to match body

### ISSUE THREAD

**Issue by dac09** [Aconex/drakov#81]
Hi,

It seems the request block on POST requests are compared to be exactly the same.

For example, from the simple API example, POSTing
```
{
    "text": "Hyperspeed jet",
    "id": "1"
}
``` 
works, however
```
{
    "text": "Hyperspeed jet",
    "id": "2"
}
``` 
results in a 404.

Any ideas how/where to fix this?

Thanks,
Danny

**Comment by dac09** [comment]
We've found how to fix it - PR coming your way from my colleague.

**Comment by yakovkhalinsky** [comment]
So now I think I understand what is happening.

If you don't want exact body matching on the request body you need to use a JSON schema.

This is expected behaviour.

We have an example in one of our test blueprint files here: https://github.com/Aconex/drakov/blob/master/test/example/md/json-schema.md

**Comment by dac09** [comment]
I see... is this the normal Apiary spec? Running the same APIB on apiary doesn't seem to cause problems.

**Comment by yakovkhalinsky** [comment]
This isn't something that is covered by the spec. The spec tells us how to document our API requests and responses.

In drakov we've chosen to implement a JSON schema then body matching as our implementation in how to respond.

Our philosophy, which keeps the code simple, is to respect the request body in the spec, unless a JSON schema exists, then we do "fuzzy" matching as long as the request conforms to the JSON schema.

The spec allows for multiple request/response pairs, so this means we keep the request/response predictable, which keeps how drakov works simple.

**Comment by dac09** [comment]
I agree, perhaps something that should go into the official Apiary spec. I've become used to having completely static / unintelligent responses from the mock server.

Thank you for the explanation, and keep up the great work!

**Comment by yakovkhalinsky** [comment]
No worries.

In the future I'm hoping to have better documentation so these sorts of things are clearer for users :+1:
