### ISSUE TITLE
How do you bind drakov to a specific interface?

### ISSUE THREAD

**Issue by khaliddermoumi** [Aconex/drakov#91]
Hello,

how do you bind drakov to a specific interface? There is a "--public" flag, but it is documented like there is no parameter to give the IP address of a specific interface.

**Comment by yakovkhalinsky** [comment]
Hi @khaliddermoumi at the moment it either binds to `locahost` by default or to all interfaces with `--public`

**Comment by khaliddermoumi** [comment]
Ok, thx!
